server:
  port: "8888"
database:
  host: "pgm-bp140jpn9wct9u0two.pg.rds.aliyuncs.com"
  port: "5432"
  user: "wws"
  password: "Wws5201314"
  dbname: "im_user"
  sslmode: "disable"
  timezone: "UTC"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 30m
  conn_max_idle_time: 5m

jwt:
  secret: "secret key"
  expire: 1h
